name: Update images

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        env:
        - { IMAGE: 'ubuntu', TAG: '16.04', DOCKERFILE: 'apt_systemd_dockerfile', BASE_IMAGE: 'ubuntu', BASE_IMAGE_TAG: '16.04' }
        - { IMAGE: 'ubuntu', TAG: '18.04', DOCKERFILE: 'apt_sysvinit-utils_dockerfile', BASE_IMAGE: 'ubuntu', BASE_IMAGE_TAG: '18.04' }
        - { IMAGE: 'centos', TAG: '6', DOCKERFILE: 'yum_initd_dockerfile', BASE_IMAGE: 'centos', BASE_IMAGE_TAG: '6' }
        - { IMAGE: 'centos', TAG: '7', DOCKERFILE: 'yum_systemd_dockerfile', BASE_IMAGE: 'centos', BASE_IMAGE_TAG: '7' }
        - { IMAGE: 'scientificlinux', TAG: '6', DOCKERFILE: 'yum_initd_dockerfile', BASE_IMAGE: 'scientificlinux/sl', BASE_IMAGE_TAG: '6' }
        - { IMAGE: 'scientificlinux', TAG: '7', DOCKERFILE: 'yum_systemd_dockerfile', BASE_IMAGE: 'scientificlinux/sl', BASE_IMAGE_TAG: '7' }
        - { IMAGE: 'oraclelinux', TAG: '6', DOCKERFILE: 'yum_initd_dockerfile', BASE_IMAGE: 'oraclelinux', BASE_IMAGE_TAG: '6' }
        - { IMAGE: 'oraclelinux', TAG: '7', DOCKERFILE: 'yum_systemd_dockerfile', BASE_IMAGE: 'oraclelinux', BASE_IMAGE_TAG: '7' }
        - { IMAGE: 'debian', TAG: '8', DOCKERFILE: 'apt_systemd_dockerfile', BASE_IMAGE: 'debian', BASE_IMAGE_TAG: '8' }
        - { IMAGE: 'debian', TAG: '9', DOCKERFILE: 'apt_systemd_dockerfile', BASE_IMAGE: 'debian', BASE_IMAGE_TAG: '9' }
        - { IMAGE: 'debian', TAG: '10', DOCKERFILE: 'apt_sysvinit-utils_dockerfile', BASE_IMAGE: 'debian', BASE_IMAGE_TAG: '10' }
    env: ${{ matrix.env }}
    steps:
      - name: Docker login
        env:
          DOCKER_CRED: '${{ secrets.DockerPassword }}'
        run: docker login -u waffleimage -p "${DOCKER_CRED}"
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: |
          docker pull $BASE_IMAGE:$BASE_IMAGE_TAG
          base_id=`docker images -q $BASE_IMAGE:$BASE_IMAGE_TAG`
          docker build --rm --no-cache -t litmusimage/$IMAGE:$TAG . --label "base_image=${base_id}" -f $DOCKERFILE --build-arg BASE_IMAGE_TAG=$BASE_IMAGE_TAG --build-arg OS_TYPE=$BASE_IMAGE
          docker push litmusimage/$IMAGE:$TAG
